### ISSUE TITLE
"Get started": Нет формата требуемых данных

### ISSUE THREAD

**Issue by dmitryvhf** [Isckatel/consumers#1]
В API есть адрес источника данных, но нет нигде информации по структуре этих данных. Желательно файл-пример.

**Comment by Isckatel** [comment]
> В API есть адрес источника данных, но нет нигде информации по структуре этих данных. Желательно файл-пример.

Что-то в этом роде? https://github.com/Isckatel/consumers/blob/master/api/sampleDataApi.js

**Comment by dmitryvhf** [comment]
"Источник данных". Даже для начальной таблицы нет никаких значений. Для симуляции 
* создал файл data.json
* положил в корень сайта
* изменил путь на источник с таргетированием на этот файл

`
[
  {
    "id": 0,
    "name": "Константин Константинович Константинопольский",
    "type": 1,
    "number": 1234567890123
  },
  {
    "id": 1,
    "name": "Иван Константинович Константинопольский",
    "type": 2,
    "number": 1334567890123
  },
  { "id": -4, "name": "Ошибочный объект", "type": 3, "number": 1634567890123 }
]
`
Но это поможет только для отображения. Для записи нет. Это же не сервис.
А ваш примеры не нужны, так как они и без симуляции создаются. Например после заполнения формы создания.

В идеале не хватает фейк-api-сервиса предоставляющего данные и обновляющие их.

**Comment by Isckatel** [comment]
> В идеале не хватает фейк-api-сервиса предоставляющего данные и обновляющие их.

Понял.
